server:
  port: 9001
spring:
  application:
    name: heimdall-center-console
  profiles:
    active: test
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
