server:
  port: 9102
spring:
  application:
    name: heimdall-center-console
  # profiles:
  #   active: test
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://82.156.161.245/center_0620
    username: root
    password: maMAm@123456root
    driver-class-name: com.mysql.cj.jdbc.Driver
